name: pure_mixpanel
description: A new pure Dart library for Mixpanel analytics.
version: 1.0.7
author: Nicholas Manning <puremixpanel@gmail.com>
homepage: https://github.com/seenickcode/pure_mixpanel

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.5
  http: ^0.12.0
  test: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.1.0 <=3.0.0"
